FROM node:20-alpine

RUN apk add --no-cache git

RUN git clone https://github.com/TorrenceB/mental-health-api.git /app

WORKDIR /app

COPY package*.json ./

RUN npm install

EXPOSE 3001

CMD ["npm", "run", "dev"]
